# services:
#   speedreaderapi:
#       # - ASPNETCORE_HTTP_PORTS=5268
#       # - ASPNETCORE_HTTPS_PORTS=5267
#     secrets:
#       - certificate_password
#     volumes:
#       - ./certificate/.aspnet/https:/home/app/.aspnet/https:ro
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/SpeedReaderAPI.pfx
#       - ASPNETCORE_Kestrel__Certificates__Default__Password=dhuiadg451
